name: CloudHub Deploment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildAndDeploy:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo   
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build And Deploy with Maven
      run: mvn -B package --file pom.xml

