name: CloudHub Deploment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildAndDeploy:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo   
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build And Deploy with Maven
      run: mvn -B clean deploy -DmuleDeploy -Dapp.runtime=4.4.0 -Dcloudhub.application.name=sbi-bank-v1-sys-api -Denvironment=Dev -Dregion=us-east-2 -Dworkers=1 -DworkerType=MICRO -Dencrypt.key=mule12345 -Dmule.env=dev --file pom.xml -s settings.xml

